# 1. Node.js 20으로 React 빌드
FROM node:20 AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
ARG REACT_APP_PUBLIC_FIREBASE_API_KEY
ARG REACT_APP_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_PUBLIC_FIREBASE_PROJECT_ID
ARG REACT_APP_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_PUBLIC_FIREBASE_APP_ID
ARG REACT_APP_PUBLIC_FIREBASE_MEASUREMENTID
ARG REACT_APP_PUBLIC_FIREBASE_VAPID_KEY
ARG REACT_APP_API_URL

# 환경 변수 주입
RUN echo "REACT_APP_PUBLIC_FIREBASE_API_KEY=$REACT_APP_PUBLIC_FIREBASE_API_KEY" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_AUTH_DOMAIN=$REACT_APP_PUBLIC_FIREBASE_AUTH_DOMAIN" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_PROJECT_ID=$REACT_APP_PUBLIC_FIREBASE_PROJECT_ID" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_STORAGE_BUCKET=$REACT_APP_PUBLIC_FIREBASE_STORAGE_BUCKET" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_APP_ID=$REACT_APP_PUBLIC_FIREBASE_APP_ID" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_MEASUREMENTID=$REACT_APP_PUBLIC_FIREBASE_MEASUREMENTID" >> .env && \
    echo "REACT_APP_PUBLIC_FIREBASE_VAPID_KEY=$REACT_APP_PUBLIC_FIREBASE_VAPID_KEY" >> .env && \
    echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env

RUN npm run build

# 2. Nginx로 정적 파일 제공
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=builder /app/build .
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
