export const corpList = [
  {
    id: 1,
    company: "삼성전자",
    sector: "전자",
    market_cap: "600조",
    stock_price: 75000,
  },
  {
    id: 2,
    company: "SK하이닉스",
    sector: "반도체",
    market_cap: "120조",
    stock_price: 125000,
  },
  {
    id: 3,
    company: "네이버",
    sector: "IT",
    market_cap: "65조",
    stock_price: 245000,
  },
  {
    id: 4,
    company: "카카오",
    sector: "IT",
    market_cap: "50조",
    stock_price: 62000,
  },
  {
    id: 5,
    company: "삼성바이오로직스",
    sector: "제약",
    market_cap: "80조",
    stock_price: 900000,
  },
  {
    id: 6,
    company: "LG에너지솔루션",
    sector: "배터리",
    market_cap: "150조",
    stock_price: 480000,
  },
  {
    id: 7,
    company: "현대자동차",
    sector: "자동차",
    market_cap: "90조",
    stock_price: 260000,
  },
  {
    id: 8,
    company: "기아",
    sector: "자동차",
    market_cap: "45조",
    stock_price: 98000,
  },
  {
    id: 9,
    company: "POSCO홀딩스",
    sector: "철강",
    market_cap: "55조",
    stock_price: 350000,
  },
  {
    id: 10,
    company: "셀트리온",
    sector: "제약",
    market_cap: "40조",
    stock_price: 150000,
  },
  {
    id: 11,
    company: "삼성SDI",
    sector: "배터리",
    market_cap: "70조",
    stock_price: 550000,
  },
  {
    id: 12,
    company: "LG화학",
    sector: "화학",
    market_cap: "80조",
    stock_price: 600000,
  },
  {
    id: 13,
    company: "삼성물산",
    sector: "건설",
    market_cap: "30조",
    stock_price: 140000,
  },
  {
    id: 14,
    company: "한화솔루션",
    sector: "에너지",
    market_cap: "20조",
    stock_price: 52000,
  },
  {
    id: 15,
    company: "한국전력",
    sector: "전력",
    market_cap: "18조",
    stock_price: 21500,
  },
  {
    id: 16,
    company: "KT&G",
    sector: "식품",
    market_cap: "15조",
    stock_price: 87000,
  },
  {
    id: 17,
    company: "SK이노베이션",
    sector: "정유",
    market_cap: "25조",
    stock_price: 180000,
  },
  {
    id: 18,
    company: "현대모비스",
    sector: "자동차부품",
    market_cap: "35조",
    stock_price: 280000,
  },
  {
    id: 19,
    company: "LG전자",
    sector: "전자",
    market_cap: "20조",
    stock_price: 120000,
  },
  {
    id: 20,
    company: "삼성전기",
    sector: "전자부품",
    market_cap: "15조",
    stock_price: 145000,
  },
  {
    id: 21,
    company: "SK텔레콤",
    sector: "통신",
    market_cap: "18조",
    stock_price: 61000,
  },
  {
    id: 22,
    company: "LG유플러스",
    sector: "통신",
    market_cap: "8조",
    stock_price: 13000,
  },
  {
    id: 23,
    company: "삼성화재",
    sector: "보험",
    market_cap: "12조",
    stock_price: 220000,
  },
  {
    id: 24,
    company: "삼성생명",
    sector: "보험",
    market_cap: "17조",
    stock_price: 80000,
  },
  {
    id: 25,
    company: "포스코퓨처엠",
    sector: "2차전지소재",
    market_cap: "14조",
    stock_price: 350000,
  },
  {
    id: 26,
    company: "하나금융지주",
    sector: "금융",
    market_cap: "13조",
    stock_price: 47500,
  },
  {
    id: 27,
    company: "KB금융",
    sector: "금융",
    market_cap: "22조",
    stock_price: 56000,
  },
  {
    id: 28,
    company: "신한지주",
    sector: "금융",
    market_cap: "19조",
    stock_price: 50000,
  },
  {
    id: 29,
    company: "우리금융지주",
    sector: "금융",
    market_cap: "10조",
    stock_price: 14000,
  },
  {
    id: 30,
    company: "카카오뱅크",
    sector: "인터넷은행",
    market_cap: "15조",
    stock_price: 32000,
  },
  {
    id: 31,
    company: "두산에너빌리티",
    sector: "에너지",
    market_cap: "9조",
    stock_price: 21000,
  },
  {
    id: 32,
    company: "HMM",
    sector: "해운",
    market_cap: "12조",
    stock_price: 19000,
  },
  {
    id: 33,
    company: "SK바이오팜",
    sector: "제약",
    market_cap: "10조",
    stock_price: 90000,
  },
  {
    id: 34,
    company: "현대건설",
    sector: "건설",
    market_cap: "8조",
    stock_price: 38000,
  },
  {
    id: 35,
    company: "LG이노텍",
    sector: "전자부품",
    market_cap: "9조",
    stock_price: 220000,
  },
  {
    id: 36,
    company: "삼성SDS",
    sector: "IT서비스",
    market_cap: "15조",
    stock_price: 155000,
  },
  {
    id: 37,
    company: "CJ제일제당",
    sector: "식품",
    market_cap: "10조",
    stock_price: 330000,
  },
  {
    id: 38,
    company: "NAVER",
    sector: "IT",
    market_cap: "70조",
    stock_price: 230000,
  },
  {
    id: 39,
    company: "카카오게임즈",
    sector: "게임",
    market_cap: "8조",
    stock_price: 43000,
  },
  {
    id: 40,
    company: "크래프톤",
    sector: "게임",
    market_cap: "12조",
    stock_price: 220000,
  },
];
