name: Deploy React Frontend to AWS EC2

on:
  push:
    branches:
      - deploy  # develop 브랜치 푸시 시 실행


jobs:
  build-and-push-frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 20
            cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: |
            export CI=false
            npm run build

      - name: Configure AWS Credentials
        run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Set Version Tag
        run: echo "VERSION_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build Frontend Docker Image
        run: |
            docker build \
              --build-arg REACT_APP_PUBLIC_FIREBASE_API_KEY=${{ secrets.REACT_APP_PUBLIC_FIREBASE_API_KEY }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_PUBLIC_FIREBASE_PROJECT_ID }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_APP_ID=${{ secrets.REACT_APP_PUBLIC_FIREBASE_APP_ID }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_MEASUREMENTID=${{ secrets.REACT_APP_PUBLIC_FIREBASE_MEASUREMENTID }} \
              --build-arg REACT_APP_PUBLIC_FIREBASE_VAPID_KEY=${{ secrets.REACT_APP_PUBLIC_FIREBASE_VAPID_KEY }} \
              --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
              -t ${{ secrets.ECR_REGISTRY }}/siungongsi:latest-frontend .

      - name: Push Frontend Docker Image
        run: |
            docker push ${{ secrets.ECR_REGISTRY }}/siungongsi:latest-frontend

  deploy:
    name: Deploy Frontend Container to EC2
    needs: [build-and-push-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                docker pull ${{ secrets.ECR_REGISTRY }}/siungongsi:latest-frontend
                docker stop frontend || true
                docker rm frontend || true
                docker run -d --name frontend -p 80:80 --restart always \
                    ${{ secrets.ECR_REGISTRY }}/siungongsi:latest-frontend
